### ISSUE TITLE
编译依赖缺失

### ISSUE THREAD

**Issue by DrAuYueng** [didi/DDMQ#12]

**Comment by DrAuYueng** [comment]
<dependency>
            <groupId>com.xiaojukeji.rocketmq</groupId>
            <artifactId>rocketmq-tools</artifactId>
            <version>4.2.2-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-tcnative</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by zenyusy** [comment]
revert to 4.2.1 please

**Comment by DrAuYueng** [comment]
> revert to 4.2.1 please

我的意思是这个依赖对应的jar没有提交至中央仓库，里面有一部分代码是调整过的，这部分没法用rocketmq官方的版本替代
<dependency>
            <groupId>com.xiaojukeji.rocketmq</groupId>
            <artifactId>rocketmq-tools</artifactId>
            <version>4.2.2-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-tcnative</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by DrAuYueng** [comment]
在rocketmq下执行：mvn clean install -DskipTests=true，本地安装后即可编译
