### ISSUE TITLE
[carrera-chronos] Is it supported to cancel delay msg?

### ISSUE THREAD

**Issue by cserwen** [didi/DDMQ#33]
如果延时消息没有过期或者失效，用户可以取消吗？如果不可以，未来有支持这个功能的想法吗？这虽然可能违背了消息队列的设计理念，但是如果支持这个功能，有些场景的业务逻辑会变得比较简单

**Comment by Jason918** [comment]
支持的，有一类特殊的取消消息，可以发送到chronos模块，类似于墓碑机制，消息到期时会自动取消投递。
参考：https://github.com/didi/DDMQ/blob/2f30b61a5741d55a5b515f3d8d19a8a35be8c9e2/carrera-sdk/producer/java/carrera-producer-sdk-example/src/main/java/com/xiaojukeji/carrera/producer/examples/CarreraProducerWithPropertiesExample.java#L100
