### ISSUE TITLE
Does java sdk or any other sdk support sending transactional message? Thanks

### ISSUE THREAD

**Issue by bopeng87** [didi/DDMQ#5]

**Comment by Zanglei06** [comment]
yes, java sdk supports sending transactional message.

**Comment by bopeng87** [comment]
I went through both carrera-sdk and carrera-producer, but didn't see any references to org.apache.rocketmq.client.producer.TransactionMQProducer. My understanding is carrera-producer should use this class to talk to rocketmq through 2PC, could u plz provide more explanation about how    carrera-producer proxy transactional msg? thx a lot

**Comment by Zanglei06** [comment]
we implement transactional messaging by ourself and didn't use TransactionMQProducer of RocketMQ. checkout demo code in CarreraTxMsgExample.
